### PR TITLE
Upgrade npm dependencies

### PR DESCRIPTION
**Pull request by kevcom**
We are using dependencies that are up to 4 years old. One even has a severe security vulnerability. `npm upgrade`.

### CODE REVIEW

**Comment by kevcom** [comment]
i will go ahead and merge. tested locally. there shouldn't be any breaking changes if all dependencies followed symver principles! we will have to rigorously test all carousels before going live.

**Comment by tracer99** [comment]
So the problem with having these dependencies out of sync with our project, is that I believe it will cause bundle bloat. We should test this out.

**Comment by kevcom** [comment]
oh good point. we'll be sure to test. but at the same time this is open source. we want to feel good that other people will be using software that's secure and up to date.

**Comment by kevcom** [comment]
how do we test for bundle bloat?

**Pull request merged**
